# testing file for Travis
# https://travis-ci.org/neuropoly/spinalcordtoolbox

sudo: false  # To use travis container infrastructure

language: python

notifications:
  slack: neuropoly:YA3mt28aeHN3A0Iu7RvMFigK
    on_success:change
    on_failure:always

# this enables to avoid recompilation of dipy if it was already compiled previously
cache:
  directories:
    - ${HOME}/.cache/pip

matrix:
  include:
    - os: linux
      python: 2.7  # these are just to make travis's UI a bit prettier
    - os: osx
      language: generic

before_install:
  - echo "HOME="
  - echo $HOME
  - sudo apt-get update -qq; sudo apt-get install -qq libopenmpi-dev; echo

env:
 - SCT_MINICONDA=2
 - SCT_MINICONDA=3

install:
# update tools
#  - ./update_bin.sh
  - yes | ./install_sct
  # run launcher in order to update PATH
  - source $HOME/build/neuropoly/spinalcordtoolbox/bin/sct_launcher
  - echo $PATH

script:
# test dependencies
#  - sct_check_dependencies
# test functions & integrity
  - if [ "$SCT_MINICONDA" == "3" ]; then sct_testing -d 1 || echo "Failure was ignored (unsupported environment)"; else sct_testing -d 1; fi
#  - python create_package.py -s ${TRAVIS_OS_NAME}  # test package creation
#  - cd ../spinalcordtoolbox_v*
#  - yes | ./install_sct  # test installation of package
  - echo "DONE"
